---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: akv2k8s-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./templates/akv2k8s/akv2k8s-workload-identity/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-infra
  timeout: 2m0s
  targetNamespace: akv2k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: akv2k8s
  namespace: flux-system
spec:
  dependsOn:
    - name: common-sources
    - name: akv2k8s-crds
  interval: 10m0s
  healthChecks:
    - kind: Deployment
      name: akv2k8s-akv2k8s-envinjector
      namespace: akv2k8s
    - kind: Deployment
      name: akv2k8s-akv2k8s-controller
      namespace: akv2k8s
  path: ./templates/akv2k8s/akv2k8s-workload-identity/helmrelease
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-infra
  timeout: 2m0s
  postBuild:
    substitute:
      registry: cdncloudsandbox.azurecr.io
      managedIdentityClientId: 00000000-0000-0000-0000-000000000000
