---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  healthChecks:
    - kind: Deployment
      name: cert-manager
      namespace: cert-manager
  interval: 10m0s
  path: ./templates/cert-manager/templates
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-infra
  timeout: 2m0s
  targetNamespace: cert-manager
  postBuild:
    substitute:
      registry: cdncloudsandbox.azurecr.io
