---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: istio
      namespace: flux-system
    - name: acme-clusterissuer
      namespace: cert-manager
  interval: 10m0s
  path: ./clusters/sa/locals/cluster-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
