apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  annotations:
    github.com/project-slug: aquijun/backstage-jm-test
spec:
  type: service
  lifecycle: production
  owner: guests
