apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service
  description: description sample
  tags:
    - tag1
  annotations:
    github.com/project-slug: aquijun/backstage-jm-test
spec:
  type: service
  owner: user:guest
  lifecycle: DEV